<?php

include( "engine/header.php" );
echo "\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/menu/EditableItem.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/menu/RangeMenu.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/grid/GridFilters.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/grid/filter/Filter.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/grid/filter/StringFilter.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/grid/filter/DateFilter.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/grid/filter/ListFilter.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/grid/filter/NumericFilter.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"js/grid/filter/BooleanFilter.js\"></script>\r\n\r\n";
echo "<s";
echo "cript type=\"text/javascript\">\r\nExt.onReady(function(){\r\nExt.BLANK_IMAGE_URL = 'js/resources/images/default/s.gif';\r\nExt.QuickTips.init();\r\n\r\n\tvar Grid;\r\n\tGrid_Title     = \"";
echo $page_title;
echo "\";\r\n\tGrid_Width     = ";
echo $this->Width;
echo ";\r\n\tGrid_Height    = ";
echo $this->Height;
echo ";\r\n\tGrid_FetchUrl  = \"";
echo $this->FetchUrl;
echo "\";\r\n\tGrid_CheckUrl  = \"";
echo $this->CheckUrl;
echo "\";\r\n\tGrid_SaveUrl   = \"";
echo $this->SaveUrl;
echo "\";\r\n\tGrid_GendocUrl = \"";
echo $this->GendocUrl;
echo "\";\r\n\tGrid_GenallUrl = \"";
echo $this->GenallUrl;
echo "\";\r\n\r\n\t";
echo $this->Html;
echo "\t";
include( "engine/checkgrid_js.php" );
echo "\t\r\n\tvar Grid_DataRecord = new Ext.data.Record.create([";
echo $this->HtmlFields;
echo "]);\r\n\tvar Grid_SelModel   = new Ext.grid.CheckboxSelectionModel();\r\n\tvar Grid_ColModel   = new Ext.grid.ColumnModel([new Ext.grid.RowNumberer(), ";
echo $this->HtmlColumns;
echo ", Grid_SelModel]);\r\n\t\t\t\r\n\tvar Grid_DataReader = new Ext.data.JsonReader({root:'results', totalProperty:'total'}, Grid_DataRecord);\r\n\tvar Grid_DataStore  = new Ext.data.GroupingStore({\r\n\t\tproxy: new Ext.data.HttpProxy({url:Grid_FetchUrl, method:'POST'}),\r\n\t\treader: Grid_DataReader, \r\n\t\tbaseParams: {dummy:0 ";
echo $this->RenderParams( );
echo "},\r\n\t\tautoLoad: {params:{start:0, limit:100 }}\r\n\t});\r\n\t\r\n\tvar Grid_Toolbar = new Ext.Toolbar({items:[\r\n\t\t{xtype: 'tbbutton',\ticon: 'img/attach.png',   cls: 'x-btn-text-icon', text: '";
echo rvx_lang( "Select records" );
echo "', handler: Grid_SelectRecords},\r\n\t\t{xtype: 'tbbutton',\ticon: 'img/filter.png',   cls: 'x-btn-text-icon', text: '";
echo rvx_lang( "Generate proposed" );
echo "', handler: Grid_GenerateDoc},\r\n\t\t{xtype: 'tbbutton',\ticon: 'img/filter.png',   cls: 'x-btn-text-icon', text: '";
echo rvx_lang( "Generate everything" );
echo "', handler: Grid_GenerateAll}\r\n\t]});\r\n\r\n\t\r\n\tGrid = new Ext.grid.EditorGridPanel({\r\n\t\theight: Grid_Height, \r\n\t\twidth: Grid_Width, \r\n\t\ttitle: Grid_Title,\r\n\t\tregion: 'center',\r\n\t\tborder: false,\r\n\t\tframe: false,\r\n\t\tloadMask: true,\r\n\t\tcolModel: Grid_ColModel, \r\n\t\tstore: Grid_DataStore, \r\n\t\tclicksToEdit: 1,\r\n\t\ttbar: Grid_Toolbar,\r\n\t\tcollapsible: true,\r\n        animCollapse: false,\r\n\t\tsm: Grid_SelModel,\r";
echo "\n\t\tplugins:[";
echo $this->HtmlPlugins;
echo "],\r\n\t\tbbar: new Ext.PagingToolbar({\r\n\t\t\tstore: Grid_DataStore,\r\n\t\t\tdisplayInfo: true,\r\n\t\t\tdisplayMsg: 'Records {0} - {1} of {2}',\r\n\t\t\temptyMsg: 'The list is empty',\r\n\t\t\tpageSize: 100\r\n\t\t})\r\n\t});\r\n\r\n\tGrid.on('validateedit', Grid_ValidateEdit, this, false);\r\n\trvxPanel = new Ext.Viewport({layout:'border',border:false,items:[Grid]});\r\n});\r\n\r\n</script>\r\n\r\n<body>\r\n</body>\r\n</html>";
?>
