INSERT INTO User(Id, GroupId, Username, Password, Passtest, LocationId, AgentId, CenterId) VALUES(1, 1, 'admin', 'admin', 'admin', '1', '1', '1');
INSERT INTO UserGroup(Id, Name) VALUES(1, 'Administrator');

INSERT INTO Company(Id, Code, Name, Version) VALUES (1,NULL,'Firma',16);
INSERT INTO Center(Id, Code, Name) VALUES (1,'1','General');
INSERT INTO Location(Id, Code, Name) VALUES (1,'1','General');
INSERT INTO Agent(Id, Code, Name) VALUES (1,'1','General');

INSERT INTO CurrencyType(Id, Code, Name) VALUES(1, 'EUR', 'Euro');
INSERT INTO CurrencyType(Id, Code, Name) VALUES(2, 'USD', 'Dolar');
INSERT INTO CurrencyType(Id, Code, Name) VALUES(3, 'GBP', 'Lira Sterlina');
INSERT INTO CurrencyType(Id, Code, Name) VALUES(4, 'RON', 'Leu Romanesc');

INSERT INTO DeliveryType(Id, Code, Name) VALUES (1,'DIRECT','Direct');
INSERT INTO DeliveryType(Id, Code, Name) VALUES (2,'POSTA','Posta');
INSERT INTO DeliveryType(Id, Code, Name) VALUES (3,'STOC','Livrare din stoc');
INSERT INTO DeliveryType(Id, Code, Name) VALUES (4,'COMD','Comanda furnizor');

INSERT INTO PaymentType(Id, Code, Name) VALUES (1,'NUMERAR','Numerar');
INSERT INTO PaymentType(Id, Code, Name) VALUES (2,'OP','Ordin de plata');
INSERT INTO PaymentType(Id, Code, Name) VALUES (3,'BO','Bilet la ordin');
INSERT INTO PaymentType(Id, Code, Name) VALUES (4,'CEC','CEC');
INSERT INTO PaymentType(Id, Code, Name) VALUES (5,'CARD','Card bancar');

INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (100,'INVENTAR','Inventar stocuri','stock_inventory', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (101,'FCUMP','Factura cumparare','buy_invoice', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (102,'FCUMPA','Factura cumparare din aviz','buy_invoice', 0, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (103,'FCUMPC','Factura cumparare din comanda','buy_invoice', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (104,'ACUMP','Aviz intrare','buy_delivery', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (105,'ACUMPF','Aviz intrare din factura','buy_delivery', 0, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (106,'ACUMPC','Aviz intrare din comanda','buy_delivery', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (107,'CCUMP','Comanda furnizor','buy_order', 0, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (201,'FVANZ','Factura vanzare','sale_invoice', 1, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (202,'FVANZA','Factura vanzare din aviz','sale_invoice', 0, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (203,'FVANZC','Factura vanzare din comanda','sale_invoice', 1, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (204,'AVANZ','Aviz iesire','sale_delivery', 1, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (205,'AVANZF','Aviz iesire din factura','sale_delivery', 0, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (206,'AVANZC','Aviz iesire din comanda','sale_delivery', 1, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (207,'CVANZ','Comanda client','sale_order', 0, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (111,'TRIN','Transfer intrare','stock_transfer', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (211,'TROUT','Transfer iesire','stock_transfer', 1, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (311,'TRANSNIR','Transfer intrare NIR','stock_transfer', 0, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (199,'REGIN','Reglaj intrare','buy_delivery', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (299,'REGOUT','Reglaj iesire','sale_delivery', 1, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (110,'FCHEL','Factura cheltuieli','buy_invoice', 0, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (130,'IMPORT','Factura import','buy_invoice', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (131,'AIC','Achizitie intracomunitara','buy_invoice', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (230,'EXPORT','Factura export','sale_invoice', 1, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (231,'LIC','Livrare intracomunitara','sale_invoice', 1, 0, 1);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (120,'BOM','Fisa tehnologica','prod_bom', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (121,'CPROD','Comanda productie','prod_order', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (122,'NPRED','Nota de predare','prod_input', 1, 1, 0);
INSERT INTO DocumentType(Id, Code, Name, Model, StockKeep, IsPositive, IsNegative) VALUES (222,'BCONS','Bon de consum','prod_output', 1, 0, 1);

INSERT INTO DocumentStatus (Id, Code, Name) VALUES(1, 'CREAT', 'Lansat');
INSERT INTO DocumentStatus (Id, Code, Name) VALUES(2, 'ANULAT', 'Anulat');
INSERT INTO DocumentStatus (Id, Code, Name) VALUES(3, 'CONFIRMAT', 'Rezervat');
INSERT INTO DocumentStatus (Id, Code, Name) VALUES(4, 'LIVRAT', 'Livrat');
INSERT INTO DocumentStatus (Id, Code, Name) VALUES(5, 'FACTURAT', 'Facturat');
INSERT INTO DocumentStatus (Id, Code, Name) VALUES(6, 'MULTI', 'Multi');
INSERT INTO DocumentStatus (Id, Code, Name) VALUES(7, 'PARTIAL', 'Partial');

INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(101, 0, 1, 1, 'VZ_19' , 'Livrari de bunuri sau prestari de servicii taxabile cota 19%', 19);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(102, 0, 1, 1, 'VZ_9'  , 'Livrari de bunuri sau prestari de servicii taxabile cota 9%', 9);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(103, 0, 1, 1, 'VZ_0'  ,  'Operatiuni neimpozabile', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(104, 0, 1, 0, 'VZ_TX' , 'Livrari de bunuri cu taxare inversa', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(105, 0, 1, 0, 'VZ_DD' , 'Alte livrari de bunuri sau prestari de servicii scutite cu drept de deducere', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(106, 0, 1, 0, 'VZ_FD' , 'Alte livrari de bunuri sau prestari de servicii scutite fara drept de deducere', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(107, 0, 1, 0, 'LIC_AD', 'Livrari intracomunitare de bunuri, scutite cf.art.143 alin.(2) lit.a) si d) din Codul Fiscal', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(108, 0, 1, 0, 'LIC_BC', 'Livrari intracomunitare de bunuri, scutite cf.art.143 alin.(2) lit.b) si c) din Codul Fiscal', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(109, 0, 1, 0, 'EXP_DD', 'Livrari de bunuri sau prestari de servicii in afara Romaniei cu drept de deducere', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(110, 0, 1, 0, 'EXP_FD', 'Livrari de bunuri sau prestari de servicii in afara Romaniei fara drept de deducere', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(111, 0, 1, 0, 'VZ_EXIG', 'Livrari de bunuri cu TVA neexigibila', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(201, 1, 0, 1, 'CU_19' , 'Achizitii de bunuri si servicii taxabile cu cota 19%', 19);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(202, 1, 0, 1, 'CU_9'  , 'Achizitii de bunuri si servicii taxabile cu cota 9%', 9);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(203, 1, 0, 1, 'CU_0'  , 'Achizitii de bunuri si servicii scutite de taxa sau neimpozabile', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(204, 1, 0, 0, 'CU_TX' , 'Achizitii de bunuri si servicii cu taxare inversa', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(205, 1, 0, 0, 'AIC_TX', 'Achizitii intracomunitare de bunuri taxare inversa', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(206, 1, 0, 0, 'CU_EXIG', 'Achizitii de bunuri cu TVA neexigibila', 0);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(120, 0, 1, 1, 'VZ_24' , 'Livrari de bunuri sau prestari de servicii taxabile cota 24%', 24);
INSERT INTO DocumentTax(Id,IsPositive,IsNegative,IsDefault,Code,Name,Percent) VALUES(220, 1, 0, 1, 'CU_24' , 'Achizitii de bunuri si servicii taxabile cu cota 24%', 24);

INSERT INTO Config(Code,Name,Value) VALUES('currency','Default currency','RON');
INSERT INTO Config(Code,Name,Value) VALUES('vat','Default vat percent','24');
INSERT INTO Config(Code,Name,Value) VALUES('item_category','Default item category','1');
INSERT INTO Config(Code,Name,Value) VALUES('item_subcategory','Default item subcategory','1');
INSERT INTO Config(Code,Name,Value) VALUES('item_brand','Default item brand','1');
INSERT INTO Config(Code,Name,Value) VALUES('item_unit','Default item unit','BUC');
INSERT INTO Config(Code,Name,Value) VALUES('item_currency', 'Default price currency', 'RON');
INSERT INTO Config(Code,Name,Value) VALUES('item_acc_income', 'Default income account', '707');
INSERT INTO Config(Code,Name,Value) VALUES('item_acc_cost', 'Default cost account', '607');
INSERT INTO Config(Code,Name,Value) VALUES('item_acc_stock', 'Default stock account', '371');
INSERT INTO Config(Code,Name,Value) VALUES('item_barcode', 'Search items by barcode', '0');
INSERT INTO Config(Code,Name,Value) VALUES('partner_category','Default partner category','1');
INSERT INTO Config(Code,Name,Value) VALUES('partner_industry','Default partner industry','1');
INSERT INTO Config(Code,Name,Value) VALUES('partner_delivery_type', 'Default delivery type', 'STOC');
INSERT INTO Config(Code,Name,Value) VALUES('partner_payment_type', 'Default payment type', 'NUMERAR');
INSERT INTO Config(Code,Name,Value) VALUES('partner_city', 'Default  partner city', 'Bucuresti');
INSERT INTO Config(Code,Name,Value) VALUES('partner_region', 'Default partner region', 'BUCURESTI');
INSERT INTO Config(Code,Name,Value) VALUES('partner_country', 'Default partner country', 'Romania');
INSERT INTO Config(Code,Name,Value) VALUES('partner_acc_supplier', 'Default supplier account', '401');
INSERT INTO Config(Code,Name,Value) VALUES('partner_acc_customer', 'Default customer account', '4111');
INSERT INTO Config(Code,Name,Value) VALUES('payment_register', 'Default payment register', 'CASA');
INSERT INTO Config(Code,Name,Value) VALUES('partner_unique_fiscal', 'Check unique fiscal code', 0 );
